// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:9d9d1bba-5b97-435b-81f8-52473a9e410f",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_1FalyrXai",
    "aws_user_pools_web_client_id": "38cegm54ve6f2m3bd09shvge9g",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://exiwktghz5cg7bsaoofed3f4ha.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "pahina2d2d892b4ceb43b7996e3ea96dfd61cb-redev",
    "aws_user_files_s3_bucket_region": "ap-southeast-1",
    "aws_mobile_analytics_app_id": "8f81b825191f46f898a8efc3eef2fbba",
    "aws_mobile_analytics_app_region": "us-west-2",
    "aws_content_delivery_bucket": "pahina-20190624230740-hostingbucket-redev",
    "aws_content_delivery_bucket_region": "ap-southeast-1",
    "aws_content_delivery_url": "http://pahina-20190624230740-hostingbucket-redev.s3-website-ap-southeast-1.amazonaws.com"
};


export default awsmobile;
