AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'SAM Template for pahina-shop-triggers

  '
Parameters:
  PahinaCaseTableStream:
    Type: String
    Default: arn:aws:dynamodb:ap-southeast-1:991300696177:table/PahinaNote-kmn6vrmi4falhppz6x5fmm4dty-dev/stream/2019-06-29T12:24:26.303
Globals:
  Function:
    Handler: index.handler
    Timeout: 3
Resources:
  PahinaNoteCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://pahina-shopifytriggers/e7f81f149815e052ed168b6e5666f701
      Runtime: nodejs10.x
      Events:
        CreateEvent:
          Type: DynamoDB
          Properties:
            Stream:
              Ref: PahinaCaseTableStream
            StartingPosition: TRIM_HORIZON
            BatchSize: 10
            Enabled: true
Outputs:
  PahinaNoteCreateFunction:
    Description: Pahina Note Create Function ARN
    Value:
      Fn::GetAtt:
      - PahinaNoteCreateFunction
      - Arn
  PahinaNoteCreateFunctionIamRole:
    Description: Implicit IAM Role created for Pahina Note Create Function
    Value:
      Fn::GetAtt:
      - PahinaNoteCreateFunctionRole
      - Arn
