AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'SAM Template for pahina-shop-triggers

  '
Parameters:
  EnvType:
    Description: Environment for this function
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - prod
    - test
  ShopifyGqlApiKey:
    Description: Shopify GraphQL API Key
    Type: AWS::SSM::Parameter::Value<String>
    Default: shpy_freemjabadilla_gql_api_key
  ShopifyGqlApiPassword:
    Description: Shopify GraphQL password
    Type: AWS::SSM::Parameter::Value<String>
    Default: shpy_freemjabadilla_gql_api_pwd
Mappings:
  PahinaCaseTblStreamArn:
    ap-southeast-1:
      dev: arn:aws:dynamodb:ap-southeast-1:991300696177:table/PahinaNote-kmn6vrmi4falhppz6x5fmm4dty-dev/stream/2019-06-29T12:24:26.303
      prod: ''
  EnvConfigMap:
    BatchSize:
      dev: 2
      prod: 10
Conditions:
  IsDev:
    Fn::Equals:
    - Ref: EnvType
    - dev
Globals:
  Function:
    Handler: index.handler
    Timeout: 3
    Environment:
      Variables:
        SHOPIFY_API_KEY:
          Ref: ShopifyGqlApiKey
        SHOPIFY_API_PWD:
          Ref: ShopifyGqlApiPassword
Resources:
  PahinaNoteCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://pahina-shopifytriggers/e7f81f149815e052ed168b6e5666f701
      Runtime: nodejs10.x
      Events:
        CreateEvent:
          Type: DynamoDB
          Properties:
            Stream:
              Fn::FindInMap:
              - PahinaCaseTblStreamArn
              - Ref: AWS::Region
              - Ref: EnvType
            StartingPosition: TRIM_HORIZON
            BatchSize:
              Fn::FindInMap:
              - EnvConfigMap
              - BatchSize
              - Ref: EnvType
            Enabled: true
Outputs:
  PahinaNoteCreateFunction:
    Description: Pahina Note Create Function ARN
    Value:
      Fn::GetAtt:
      - PahinaNoteCreateFunction
      - Arn
  PahinaNoteCreateFunctionIamRole:
    Description: Implicit IAM Role created for Pahina Note Create Function
    Value:
      Fn::GetAtt:
      - PahinaNoteCreateFunctionRole
      - Arn
