AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'SAM Template for pahina-shop-triggers

  '
Parameters:
  EnvType:
    Description: Environment for this function
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - prod
    - test
    - NONE
  ShopifyApiHost:
    Description: Shopify hostname
    Type: String
    Default: freelitemjabadilla.myshopify.com
  ShopifyApiVersion:
    Description: Shopify API version
    Type: String
    Default: 2019-07
    AllowedValues:
    - 2019-07
Mappings:
  EnvConfigMap:
    BatchSize:
      dev: 1
      prod: 10
  AmplifyProject:
    GraphQLAPIIdOutput:
      dev: qljbda6ysjbvvkl6tm53ohjgey
      prod: ''
Conditions:
  IsDev:
    Fn::Equals:
    - Ref: EnvType
    - dev
  ShouldNotCreateEnvResources:
    Fn::Equals:
    - Ref: EnvType
    - NONE
Globals:
  Function:
    Handler: app.handler
    Timeout: 30
    Runtime: nodejs10.x
    Environment:
      Variables:
        SHOPIFY_API_HOSTNAME:
          Ref: ShopifyApiHost
        REGION:
          Ref: AWS::Region
        ENV:
          Ref: EnvType
Resources:
  NoteStreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://pahina-shopify-triggers/e7136627dab4bbb633f1be119b6f3cef
      Timeout: 240
      Events:
        StreamEvent:
          Type: DynamoDB
          Properties:
            Stream:
              Fn::ImportValue:
                Fn::Join:
                - ':'
                - - Fn::FindInMap:
                    - AmplifyProject
                    - GraphQLAPIIdOutput
                    - Ref: EnvType
                  - GetAtt
                  - PahinaNoteTable
                  - StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize:
              Fn::FindInMap:
              - EnvConfigMap
              - BatchSize
              - Ref: EnvType
            Enabled: true
      Environment:
        Variables:
          SHOPIFY_API_HOSTNAME:
            Ref: ShopifyApiHost
          SHOPIFY_API_VERSION:
            Ref: ShopifyApiVersion
          USER_TABLE_NAME:
            Fn::ImportValue:
              Fn::Join:
              - ':'
              - - Fn::FindInMap:
                  - AmplifyProject
                  - GraphQLAPIIdOutput
                  - Ref: EnvType
                - GetAtt
                - PahinaUserTable
                - Name
          USER_STORE_TABLE_NAME:
            Fn::ImportValue:
              Fn::Join:
              - ':'
              - - Fn::FindInMap:
                  - AmplifyProject
                  - GraphQLAPIIdOutput
                  - Ref: EnvType
                - GetAtt
                - PahinaUserStoreTable
                - Name
          USER_STORE_PRODUCT_TABLE_NAME:
            Fn::ImportValue:
              Fn::Join:
              - ':'
              - - Fn::FindInMap:
                  - AmplifyProject
                  - GraphQLAPIIdOutput
                  - Ref: EnvType
                - GetAtt
                - PahinaUserStoreProductTable
                - Name
      Policies:
      - SSMParameterReadPolicy:
          ParameterName: /freelitemjabadilla.myshopify.com/dev/ApiKey
      - SSMParameterReadPolicy:
          ParameterName: /freelitemjabadilla.myshopify.com/dev/Password
      - SSMParameterReadPolicy:
          ParameterName: /freelitemjabadilla.myshopify.com/dev/SharedSecret
      - DynamoDBCrudPolicy:
          TableName:
            Fn::ImportValue:
              Fn::Join:
              - ':'
              - - Fn::FindInMap:
                  - AmplifyProject
                  - GraphQLAPIIdOutput
                  - Ref: EnvType
                - GetAtt
                - PahinaCaseTable
                - Name
      - DynamoDBCrudPolicy:
          TableName:
            Fn::ImportValue:
              Fn::Join:
              - ':'
              - - Fn::FindInMap:
                  - AmplifyProject
                  - GraphQLAPIIdOutput
                  - Ref: EnvType
                - GetAtt
                - PahinaUserTable
                - Name
  UserStreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://pahina-shopify-triggers/4a4f5c23e3c4ef671665ca0ee4736c4d
      Environment:
        Variables:
          USER_STORE_TABLE_NAME:
            Fn::ImportValue:
              Fn::Join:
              - ':'
              - - Fn::FindInMap:
                  - AmplifyProject
                  - GraphQLAPIIdOutput
                  - Ref: EnvType
                - GetAtt
                - PahinaUserStoreTable
                - Name
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Fn::ImportValue:
              Fn::Join:
              - ':'
              - - Fn::FindInMap:
                  - AmplifyProject
                  - GraphQLAPIIdOutput
                  - Ref: EnvType
                - GetAtt
                - PahinaUserStoreTable
                - Name
      Events:
        StreamEvent:
          Type: DynamoDB
          Properties:
            Stream:
              Fn::ImportValue:
                Fn::Join:
                - ':'
                - - Fn::FindInMap:
                    - AmplifyProject
                    - GraphQLAPIIdOutput
                    - Ref: EnvType
                  - GetAtt
                  - PahinaUserTable
                  - StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 1
            Enabled: true
Outputs:
  NoteStreamFunction:
    Description: NoteStream Function ARN
    Value:
      Fn::GetAtt:
      - NoteStreamFunction
      - Arn
  NoteStreamFunctionIamRole:
    Description: Implicit IAM Role created for NoteStream Function
    Value:
      Fn::GetAtt:
      - NoteStreamFunctionRole
      - Arn
  UserStreamFunction:
    Description: UserStream Function ARN
    Value:
      Fn::GetAtt:
      - UserStreamFunction
      - Arn
  UserStreamFunctionIamRole:
    Description: Implicit IAM Role created for UserStream Function
    Value:
      Fn::GetAtt:
      - UserStreamFunctionRole
      - Arn
