AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'SAM Template for pahina-shop-triggers

  '
Parameters:
  EnvType:
    Description: Environment for this function
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - prod
    - test
    - NONE

  ShopifyApiHost:
    Description: 'Shopify hostname'
    Type: String
    Default: 'freelitemjabadilla.myshopify.com' 

  ShopifyApiVersion:
    Description: 'Shopify API version'
    Type: String
    Default: '2019-07'
    AllowedValues: 
      - 2019-07
Mappings:
  EnvConfigMap:
    BatchSize:
      dev: 1
      prod: 10
  AmplifyProject:
    GraphQLAPIIdOutput:
      dev: kbpidncxhven5asuuuyqocnffm
      prod: ''
    UserPoolId:
      dev: ap-southeast-1_1CQQvDhhM
      prod: ''
Conditions:
  IsDev:
    Fn::Equals:
    - Ref: EnvType
    - dev
  ShouldNotCreateEnvResources:
    Fn::Equals: [ !Ref EnvType, "NONE"]
Globals:
  Function:
    Tracing: Active
    Handler: app.handler
    Timeout: 30
    Runtime: nodejs10.x
    Environment:
      Variables:
        SHOPIFY_API_HOSTNAME: !Ref ShopifyApiHost
        SHOPIFY_API_VERSION: !Ref ShopifyApiVersion
        USER_POOL_ID: !FindInMap [AmplifyProject, UserPoolId, !Ref EnvType]
        REGION: !Ref AWS::Region
        ENV: !Ref EnvType

Resources:
  NoteStreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: note-stream/lib
      MemorySize: 256
      Timeout: 240
      Events:
        StreamEvent:
          Type: DynamoDB
          Properties:
            Stream:
              Fn::ImportValue:
                !Join
                  - ":"
                  - - !FindInMap
                      - "AmplifyProject"
                      - "GraphQLAPIIdOutput"
                      - !Ref EnvType
                    - "GetAtt"
                    - "PahinaNoteTable"
                    - "StreamArn"
            StartingPosition: TRIM_HORIZON
            BatchSize:
              Fn::FindInMap:
              - EnvConfigMap
              - BatchSize
              - Ref: EnvType
            Enabled: true
      Environment: 
        Variables:
          USER_TABLE_NAME:
            Fn::ImportValue:
              !Join 
                - ":"
                - - !FindInMap 
                    - "AmplifyProject"
                    - "GraphQLAPIIdOutput"
                    - !Ref EnvType
                  - "GetAtt"
                  - "PahinaUserTable"
                  - "Name"
          USER_STORE_TABLE_NAME:
            Fn::ImportValue:
              !Join 
                - ":"
                - - !FindInMap 
                    - "AmplifyProject"
                    - "GraphQLAPIIdOutput"
                    - !Ref EnvType
                  - "GetAtt"
                  - "PahinaUserStoreTable"
                  - "Name"
          CASE_TABLE_NAME:
            Fn::ImportValue:
              !Join 
                - ":"
                - - !FindInMap 
                    - "AmplifyProject"
                    - "GraphQLAPIIdOutput"
                    - !Ref EnvType
                  - "GetAtt"
                  - "PahinaCaseTable"
                  - "Name"
          USER_STORE_PRODUCT_TABLE_NAME:
            Fn::ImportValue:
              !Join 
                - ":"
                - - !FindInMap 
                    - "AmplifyProject"
                    - "GraphQLAPIIdOutput"
                    - !Ref EnvType
                  - "GetAtt"
                  - "PahinaUserStoreProductTable"
                  - "Name"
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Fn::ImportValue:
                !Join 
                  - ":"
                  - - !FindInMap 
                      - "AmplifyProject"
                      - "GraphQLAPIIdOutput"
                      - !Ref EnvType
                    - "GetAtt"
                    - "PahinaCaseTable"
                    - "Name"
        - DynamoDBCrudPolicy:
            TableName:
              Fn::ImportValue:
                !Join 
                  - ":"
                  - - !FindInMap 
                      - "AmplifyProject"
                      - "GraphQLAPIIdOutput"
                      - !Ref EnvType
                    - "GetAtt"
                    - "PahinaUserTable"
                    - "Name"
        - DynamoDBCrudPolicy:
            TableName:
              Fn::ImportValue:
                !Join 
                  - ":"
                  - - !FindInMap 
                      - "AmplifyProject"
                      - "GraphQLAPIIdOutput"
                      - !Ref EnvType
                    - "GetAtt"
                    - "PahinaUserStoreTable"
                    - "Name"
        - DynamoDBCrudPolicy:
            TableName:
              Fn::ImportValue:
                !Join 
                  - ":"
                  - - !FindInMap 
                      - "AmplifyProject"
                      - "GraphQLAPIIdOutput"
                      - !Ref EnvType
                    - "GetAtt"
                    - "PahinaUserStoreProductTable"
                    - "Name"
        - Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - ssm:DescribeParameters
            Resource: "*"
          - Sid: VisualEditor1
            Effect: Allow
            Action:
            - ssm:GetParameters
            - ssm:GetParameter
            Resource: !Sub [ "arn:aws:ssm:${AWS::Region}:*:parameter/${host}/${env}/*", { "host": !Ref ShopifyApiHost, "env": !Ref EnvType }]
          - Sid: VisualEditor2
            Effect: Allow
            Action:
            - ssm:GetParametersByPath
            Resource: !Sub
              - arn:aws:ssm:${AWS::Region}:*:parameter/${host}/${env}
              - { "host": !Ref ShopifyApiHost, "env": !Ref EnvType }
          - Sid: VisualEditor3
            Effect: Allow
            Action:
            - cognito-idp:AdminGetUser
            Resource: !Sub
              - arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${poolid}
              - { "poolid": !FindInMap [AmplifyProject, UserPoolId, !Ref EnvType] }
  UserStreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user-stream/lib
      Environment:
        Variables:
          USER_STORE_TABLE_NAME:
            Fn::ImportValue:
              !Join 
                - ":"
                - - !FindInMap 
                    - "AmplifyProject"
                    - "GraphQLAPIIdOutput"
                    - !Ref EnvType
                  - "GetAtt"
                  - "PahinaUserStoreTable"
                  - "Name"
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Fn::ImportValue:
                !Join 
                  - ":"
                  - - !FindInMap 
                      - "AmplifyProject"
                      - "GraphQLAPIIdOutput"
                      - !Ref EnvType
                    - "GetAtt"
                    - "PahinaUserStoreTable"
                    - "Name"
        - Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - ssm:DescribeParameters
            Resource: "*"
          - Sid: VisualEditor1
            Effect: Allow
            Action:
            - ssm:GetParameters
            - ssm:GetParameter
            Resource: !Sub [ "arn:aws:ssm:${AWS::Region}:*:parameter/${host}/${env}/*", { "host": !Ref ShopifyApiHost, "env": !Ref EnvType }]
          - Sid: VisualEditor2
            Effect: Allow
            Action:
            - ssm:GetParametersByPath
            Resource: !Sub
              - arn:aws:ssm:${AWS::Region}:*:parameter/${host}/${env}
              - { "host": !Ref ShopifyApiHost, "env": !Ref EnvType }
          - Sid: VisualEditor3
            Effect: Allow
            Action:
            - cognito-idp:AdminGetUser
            Resource: !Sub
              - arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${poolid}
              - { "poolid": !FindInMap [AmplifyProject, UserPoolId, !Ref EnvType] }
      Events:
        StreamEvent:
          Type: DynamoDB
          Properties:
            Stream:
              Fn::ImportValue:
                !Join 
                  - ":"
                  - - !FindInMap 
                      - "AmplifyProject"
                      - "GraphQLAPIIdOutput"
                      - !Ref EnvType
                    - "GetAtt"
                    - "PahinaUserTable"
                    - "StreamArn"
            StartingPosition: TRIM_HORIZON
            BatchSize: 1
            Enabled: true
  
Outputs:
  NoteStreamFunction:
    Description: NoteStream Function ARN
    Value:
      Fn::GetAtt:
      - NoteStreamFunction
      - Arn
  NoteStreamFunctionIamRole:
    Description: Implicit IAM Role created for NoteStream Function
    Value:
      Fn::GetAtt:
      - NoteStreamFunctionRole
      - Arn
  UserStreamFunction:
    Description: UserStream Function ARN
    Value:
      Fn::GetAtt:
      - UserStreamFunction
      - Arn
  UserStreamFunctionIamRole:
    Description: Implicit IAM Role created for UserStream Function
    Value:
      Fn::GetAtt:
      - UserStreamFunctionRole
      - Arn

