AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'SAM Template for pahina-shop-triggers

  '
Parameters:
  EnvType:
    Description: Environment for this function
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - prod
    - test
  ShopifyApiKey:
    Description: Shopify API Key
    Type: AWS::SSM::Parameter::Value<String>
    Default: shpy_freemjabadilla_gql_api_key
  ShopifyApiPwd:
    Description: Shopify password
    Type: AWS::SSM::Parameter::Value<String>
    Default: shpy_freemjabadilla_gql_api_pwd
  ShopifyGqlApiHost:
    Description: Shopify hostname
    Type: String
    Default: freemjabadilla.myshopify.com
  GraphQLAPIIdOutput:
    Description: AppSync prefix for API ID Output
    Type: String
Mappings:
  EnvConfigMap:
    BatchSize:
      dev: 2
      prod: 10
  AmplifyProject:
    GraphQLAPIIdOutput:
      dev: 3zapujkk4jen5pg5c6gkouinom
      prod: ''
Conditions:
  IsDev:
    Fn::Equals:
    - Ref: EnvType
    - dev
Globals:
  Function:
    Handler: app.handler
    Timeout: 3
    Environment:
      Variables:
        SHOPIFY_API_KEY:
          Ref: ShopifyApiKey
        SHOPIFY_API_PWD:
          Ref: ShopifyApiPwd
        SHOPIFY_API_HOSTNAME:
          Ref: ShopifyGqlApiHost
        
Resources:
  NoteStreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: note-stream/dist/
      Runtime: nodejs10.x
      Events:
        StreamEvent:
          Type: DynamoDB
          Properties:
            Stream:
              Fn::ImportValue:
                !Join [":", [ !FindInMap [ "AmplifyProject", "GraphQLAPIIdOutput", !Ref EnvType ], "GetAtt", "PahinaNoteTable", "StreamArn" ] ]
            StartingPosition: TRIM_HORIZON
            BatchSize:
              Fn::FindInMap:
              - EnvConfigMap
              - BatchSize
              - Ref: EnvType
            Enabled: true
  UserStreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user-stream/dist
      Runtime: nodejs10.x
      Events:
        StreamEvent:
          Type: DynamoDB
          Properties:
            Stream:
              Fn::ImportValue:
                !Join [":", [ !FindInMap [ "AmplifyProject", "GraphQLAPIIdOutput", !Ref EnvType ], "GetAtt", "PahinaUserTable", "StreamArn" ] ]
            StartingPosition: TRIM_HORIZON
            BatchSize:
              Fn::FindInMap:
              - EnvConfigMap
              - BatchSize
              - Ref: EnvType
            Enabled: true
Outputs:
  NoteStreamFunction:
    Description: NoteStream Function ARN
    Value:
      Fn::GetAtt:
      - NoteStreamFunction
      - Arn
  NoteStreamFunctionIamRole:
    Description: Implicit IAM Role created for NoteStream Function
    Value:
      Fn::GetAtt:
      - NoteStreamFunctionRole
      - Arn
  UserStreamFunction:
    Description: UserStream Function ARN
    Value:
      Fn::GetAtt:
      - UserStreamFunction
      - Arn
  UserStreamFunctionIamRole:
    Description: Implicit IAM Role created for UserStream Function
    Value:
      Fn::GetAtt:
      - UserStreamFunctionRole
      - Arn

