AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'SAM Template for pahina-shop-triggers

  '
Parameters:
  EnvType:
    Description: Environment for this function
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - prod
    - test
  ShopifyApiKey:
    Description: Shopify API Key
    Type: AWS::SSM::Parameter::Value<String>
    Default: shpy_freemjabadilla_gql_api_key
  ShopifyApiPwd:
    Description: Shopify password
    Type: AWS::SSM::Parameter::Value<String>
    Default: shpy_freemjabadilla_gql_api_pwd
  ShopifyGqlApiHost:
    Description: Shopify hostname
    Type: String
    Default: freemjabadilla.myshopify.com
Mappings:
  CaseTblStreamArn:
    ap-southeast-1:
      dev: arn:aws:dynamodb:ap-southeast-1:991300696177:table/PahinaNote-bafaeahnlnesxg65deloyiar4m-dev/stream/2019-07-08T21:18:53.408
      prod: ''
  EnvConfigMap:
    BatchSize:
      dev: 2
      prod: 10
Conditions:
  IsDev:
    Fn::Equals:
    - Ref: EnvType
    - dev
Globals:
  Function:
    Handler: app.handler
    Timeout: 3
    Environment:
      Variables:
        SHOPIFY_API_KEY:
          Ref: ShopifyApiKey
        SHOPIFY_API_PWD:
          Ref: ShopifyApiPwd
        SHOPIFY_API_HOSTNAME:
          Ref: ShopifyGqlApiHost
Resources:
  NoteStreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: note-stream/dist/
      Runtime: nodejs10.x
      Events:
        StreamEvent:
          Type: DynamoDB
          Properties:
            Stream:
              Fn::FindInMap:
              - CaseTblStreamArn
              - Ref: AWS::Region
              - Ref: EnvType
            StartingPosition: TRIM_HORIZON
            BatchSize:
              Fn::FindInMap:
              - EnvConfigMap
              - BatchSize
              - Ref: EnvType
            Enabled: true
Outputs:
  NoteStreamFunction:
    Description: NoteStream Function ARN
    Value:
      Fn::GetAtt:
      - NoteStreamFunction
      - Arn
  NoteStreamFunctionIamRole:
    Description: Implicit IAM Role created for NoteStream Function
    Value:
      Fn::GetAtt:
      - NoteStreamFunctionRole
      - Arn
