projects:
  pahinaapi:
    schemaPath: src/graphql/schema.json
    includes:
      - src/shared/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/shared/API.ts
        docsFilePath: src/shared/graphql
        maxDepth: 3
