// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:84b23718-6c44-4361-b0a1-7ff8c43f2db5",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_J5ly3RHtS",
    "aws_user_pools_web_client_id": "60f226pbqif0ant8t611kg0dsd",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://jlan37ffw5hhnlh6arz6zr6cne.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "pahina2d2d892b4ceb43b7996e3ea96dfd61cb-bugbug",
    "aws_user_files_s3_bucket_region": "ap-southeast-1",
    "aws_mobile_analytics_app_id": "09912724f9bb46d38f1be0774549edbe",
    "aws_mobile_analytics_app_region": "us-west-2",
    "aws_content_delivery_bucket": "pahina-20190624230740-hostingbucket-bugbug",
    "aws_content_delivery_bucket_region": "ap-southeast-1",
    "aws_content_delivery_url": "http://pahina-20190624230740-hostingbucket-bugbug.s3-website-ap-southeast-1.amazonaws.com"
};


export default awsmobile;
